export const WEAPONS = [
  {
    id: 'shell',
    label: 'Basic Shell',
    speedFactor: 1,
    gravityScale: 1,
    windScale: 1,
    blastRadius: 36,
    damage: 42,
    projectileRadius: 5,
    color: 0xfce7a1,
    predictionTime: 2.1,
    muzzleColor: 0xffe2a1,
    trailWidth: 2.8,
    trailAlpha: 0.42,
    trailLength: 10,
    burstCount: 10,
    flashScale: 2,
    explosionCore: 0xffefb5,
    explosionRing: 0xff9258,
    damageText: '#ffd98b'
  },
  {
    id: 'mortar',
    label: 'Heavy Mortar',
    speedFactor: 0.76,
    gravityScale: 1.22,
    windScale: 0.68,
    blastRadius: 52,
    damage: 60,
    projectileRadius: 6,
    color: 0xff9e57,
    predictionTime: 2.4,
    muzzleColor: 0xffb06d,
    trailWidth: 4,
    trailAlpha: 0.5,
    trailLength: 12,
    burstCount: 16,
    flashScale: 2.6,
    explosionCore: 0xffd0a8,
    explosionRing: 0xff6d3d,
    damageText: '#ffb26b'
  },
  {
    id: 'split',
    label: 'Split Shot',
    speedFactor: 0.92,
    gravityScale: 0.95,
    windScale: 1.15,
    blastRadius: 24,
    damage: 24,
    projectileRadius: 4,
    color: 0x8ff7ef,
    predictionTime: 1.7,
    splitDelay: 0.72,
    childCount: 3,
    childSpread: 0.28,
    childSpeedFactor: 0.9,
    childLift: -55,
    muzzleColor: 0xbafcf4,
    trailWidth: 2.2,
    trailAlpha: 0.38,
    trailLength: 8,
    burstCount: 12,
    flashScale: 2.2,
    explosionCore: 0xd9fffb,
    explosionRing: 0x59e8d7,
    damageText: '#9ef7ef'
  },
  {
    id: 'bouncer',
    label: 'Bouncer',
    speedFactor: 0.86,
    gravityScale: 1.08,
    windScale: 0.75,
    blastRadius: 28,
    damage: 38,
    projectileRadius: 5,
    color: 0x98ff8c,
    predictionTime: 2.8,
    maxBounces: 3,
    restitution: 0.60,
    muzzleColor: 0xb8ffa8,
    trailWidth: 2.4,
    trailAlpha: 0.44,
    trailLength: 11,
    burstCount: 11,
    flashScale: 2.2,
    explosionCore: 0xd4ffd4,
    explosionRing: 0x44bb44,
    damageText: '#98ff8c'
  }
];

export function getWeapon(index) {
  return WEAPONS[((index % WEAPONS.length) + WEAPONS.length) % WEAPONS.length];
}
