// ammo: null = unlimited, number = finite per match
export const WEAPONS = [
  {
    id: 'shell',
    label: 'Basic Shell',
    ammo: null,
    rarity: 'common',
    speedFactor: 1,
    gravityScale: 1,
    windScale: 1,
    blastRadius: 36,
    damage: 42,
    projectileRadius: 5,
    color: 0xfce7a1,
    predictionTime: 2.1,
    muzzleColor: 0xffe2a1,
    trailWidth: 2.8,
    trailAlpha: 0.42,
    trailLength: 10,
    burstCount: 10,
    flashScale: 2,
    explosionCore: 0xffefb5,
    explosionRing: 0xff9258,
    damageText: '#ffd98b'
  },
  {
    id: 'mortar',
    label: 'Heavy Mortar',
    ammo: 5,
    rarity: 'rare',
    speedFactor: 0.76,
    gravityScale: 1.22,
    windScale: 0.68,
    blastRadius: 52,
    damage: 60,
    projectileRadius: 6,
    color: 0xff9e57,
    predictionTime: 2.4,
    muzzleColor: 0xffb06d,
    trailWidth: 4,
    trailAlpha: 0.5,
    trailLength: 12,
    burstCount: 16,
    flashScale: 2.6,
    explosionCore: 0xffd0a8,
    explosionRing: 0xff6d3d,
    damageText: '#ffb26b'
  },
  {
    id: 'split',
    label: 'Split Shot',
    ammo: 3,
    rarity: 'rare',
    speedFactor: 0.92,
    gravityScale: 0.95,
    windScale: 1.15,
    blastRadius: 24,
    damage: 24,
    projectileRadius: 4,
    color: 0x8ff7ef,
    predictionTime: 1.7,
    splitDelay: 0.72,
    childCount: 3,
    childSpread: 0.28,
    childSpeedFactor: 0.9,
    childLift: -55,
    muzzleColor: 0xbafcf4,
    trailWidth: 2.2,
    trailAlpha: 0.38,
    trailLength: 8,
    burstCount: 12,
    flashScale: 2.2,
    explosionCore: 0xd9fffb,
    explosionRing: 0x59e8d7,
    damageText: '#9ef7ef'
  },
  {
    id: 'bouncer',
    label: 'Bouncer',
    ammo: 3,
    rarity: 'rare',
    speedFactor: 0.86,
    gravityScale: 1.08,
    windScale: 0.75,
    blastRadius: 28,
    damage: 38,
    projectileRadius: 5,
    color: 0x98ff8c,
    predictionTime: 2.8,
    maxBounces: 3,
    restitution: 0.60,
    muzzleColor: 0xb8ffa8,
    trailWidth: 2.4,
    trailAlpha: 0.44,
    trailLength: 11,
    burstCount: 11,
    flashScale: 2.2,
    explosionCore: 0xd4ffd4,
    explosionRing: 0x44bb44,
    damageText: '#98ff8c'
  },
  {
    id: 'rail',
    label: 'Rail Slug',
    ammo: 3,
    rarity: 'rare',
    speedFactor: 1.34,
    gravityScale: 0.78,
    windScale: 0.32,
    blastRadius: 14,
    damage: 50,
    projectileRadius: 4,
    color: 0xc7f4ff,
    predictionTime: 1.9,
    muzzleColor: 0xe8fbff,
    trailWidth: 2,
    trailAlpha: 0.34,
    trailLength: 12,
    burstCount: 9,
    flashScale: 2.1,
    explosionCore: 0xe8fbff,
    explosionRing: 0x72d9ff,
    damageText: '#c8f2ff'
  },
  {
    id: 'splitstorm',
    label: 'Storm Shards',
    ammo: 2,
    rarity: 'epic',
    speedFactor: 0.98,
    gravityScale: 0.9,
    windScale: 1.18,
    blastRadius: 16,
    damage: 15,
    projectileRadius: 4,
    color: 0xc9b7ff,
    predictionTime: 1.8,
    splitDelay: 0.52,
    childCount: 5,
    childSpread: 0.18,
    childSpeedFactor: 0.82,
    childLift: -38,
    muzzleColor: 0xe3dbff,
    trailWidth: 2.1,
    trailAlpha: 0.4,
    trailLength: 8,
    burstCount: 15,
    flashScale: 2.4,
    explosionCore: 0xf0ebff,
    explosionRing: 0x9f82ff,
    damageText: '#ddd1ff'
  },
  {
    id: 'hopper',
    label: 'Hopper Mine',
    ammo: 2,
    rarity: 'rare',
    speedFactor: 0.9,
    gravityScale: 1.05,
    windScale: 0.72,
    blastRadius: 26,
    damage: 30,
    projectileRadius: 5,
    color: 0xffb85b,
    predictionTime: 3,
    maxBounces: 4,
    restitution: 0.68,
    muzzleColor: 0xffcf94,
    trailWidth: 2.6,
    trailAlpha: 0.46,
    trailLength: 12,
    burstCount: 13,
    flashScale: 2.3,
    explosionCore: 0xffe1bf,
    explosionRing: 0xff8e3c,
    damageText: '#ffc27a'
  }
];

export function getWeapon(index) {
  return WEAPONS[((index % WEAPONS.length) + WEAPONS.length) % WEAPONS.length];
}
